config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "schedules#index"
  resources :teams
  resources :schedules
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/accuracy.rb
class Accuracy < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '仮予約' },
    { id: 3, name: '本予約' },
    { id: 4, name: '夜間明け' },
    { id: 5, name: 'その他' },

  ]

  include ActiveHash::Associations
  has_many :schedules

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/first_contact.rb
class FirstContact < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '商社' },
    { id: 3, name: '営業' },
    { id: 4, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :schedules

end

app/models/mie.rb
class Mie < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '伊賀' },
    { id: 3, name: '伊勢' },
    { id: 4, name: 'いなべ' },
    { id: 5, name: '尾鷲' },
    { id: 6, name: '亀山' },
    { id: 7, name: '熊野' },
    { id: 8, name: '桑名' },
    { id: 9, name: '志摩' },
    { id: 10, name: '鈴鹿' },
    { id: 11, name: '津' },
    { id: 12, name: '鳥羽' },
    { id: 13, name: '名張' },
    { id: 14, name: '松坂' },
    { id: 15, name: '四日市' },
  ]

  include ActiveHash::Associations
  has_many :schedules

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :time_zone
  belongs_to :user
  belongs_to :team
  belongs_to :size
  belongs_to :accuracy
  belongs_to :first_contact
  belongs_to :mie

  with_options presence: true do
    validates :scheduled_date, uniqueness: { scope: [:time_zone_id, :team_id], message: "は既に埋まっています" }
    validates :time_zone_id, :size_id, :accuracy_id, :first_contact_id,
    numericality: { other_than: 1, message: " can't be blank" }
    validates :mie_id, {numericality: true}
  end

end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '小' },
    { id: 3, name: '中' },
    { id: 4, name: '大' },
    { id: 5, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :schedules

end

app/models/team.rb
class Team < ApplicationRecord
  validates :team_name, :affiliation, presence: true
  validates :work, inclusion: {in: [true, false]}
  has_many :schedules
end

app/models/time_zone.rb
class TimeZone < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '午前' },
    { id: 3, name: '午後' },
    { id: 4, name: '夜間' },
  ]

  include ActiveHash::Associations
  has_many :schedules

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: ' は有効でありません。' }
  validates :admin, inclusion: {in: [true, false]}
  
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'

  has_many :schedules

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def index
    get_week    
    @teams = Team.where(work: '1')
    @schedules = Schedule.where(scheduled_date: @todays_date..@todays_date + 6)

  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
      @schedule = Schedule.find(params[:id])
      @schedule.delete
      redirect_to root_path
  end
  
  private

  def schedule_params
    params.require(:schedule).permit(:scheduled_date, :time_zone_id, :team_id, :size_id, :mie_id, :accuracy_id, :first_contact_id).merge(user_id: current_user.id)
  end  

  def get_week
    # カレンダーに日付データ曜日を持たせる
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    @todays_date = Date.today

    @week_days = []

    7.times do |x|

      wday_num = Date.today.wday + x
      if  wday_num >= 7
        wday_num = wday_num -7
      end

      today_days = { scheduled_date:(@todays_date + x), month: (@todays_date + x).month, date: (@todays_date + x).day, wday:  wdays[wday_num]}

      @week_days.push(today_days)
    end
  end


end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to teams_path
    else
      render :new
    end
  end

  def edit
    @team = Team.find(params[:id])

  end

  private

  def team_params
    params.require(:team).permit(:team_name, :affiliation, :work )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakunin06</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <% if user_signed_in? %>
      <div class="nav__right">
          <%= link_to current_user.email, "#", class: "user-email"  %> 
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
          <%= link_to "新規予約", new_schedule_path, class: :nav__btn %>
          <%= link_to "班一覧", teams_path, class: :nav__btn %>
          <%= link_to "新規班作成", new_team_path, class: :nav__btn %>
          <%= link_to "トップページ", root_path, class: :nav__btn %>
        </div> 
        <% else %>
        <div class="nav__right">
        <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
        <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class="schedule_edit">予約内容を変更する</div>
<%= form_with model: @schedule, url: schedule_path, method: :put, local: true do |f| %>
<div class="hissu_input">必須項目</div>
<%= f.label :日付を選択, class: 'lavel' %>
<%= f.date_field :scheduled_date, class: 'date-select' %>
<%= f.label :施工班を選択, class: 'lavel' %>
<%= f.collection_select(:team_id, Team.where(work: '1'), :id, :team_name, {}, {class:"team-select"}) %>
<%= f.label :時間帯を選択, class: 'lavel' %>
<%= f.collection_select(:time_zone_id, TimeZone.all, :id, :name, {}, {class:"time_zone-select"}) %>
<%= f.label :サイズを選択, class: 'lavel' %>
<%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"size-select"}) %>
<%= f.label :予約確度を選択, class: 'lavel' %>
<%= f.collection_select(:accuracy_id, Accuracy.all, :id, :name, {}, {class:"accuracy-select"}) %>
<%= f.label :場所を選択, class: 'lavel' %>
<%= f.collection_select(:mie_id, Mie.all, :id, :name, {}, {class:"mie-select"}) %>
<%= f.label :連絡元を選択, class: 'lavel' %>
<%= f.collection_select(:first_contact_id, FirstContact.all, :id, :name, {}, {class:"first_contact-select"}) %>
<%= f.submit "予約を変更する" %>
<% end %>

<%
=begin
%>
<div class="schedule_copy_create">予約内容をコピーして新規予約をする</div>
<%= form_with model: @schedule, url: schedules_path, method: :post, local: true do |f| %>
<div class="hissu_input">必須項目</div>
<%= f.label :日付を選択, class: 'lavel' %>
<%= f.date_field :scheduled_date, class: 'date-select' %>
<%= f.label :施工班を選択, class: 'lavel' %>
<%= f.collection_select(:team_id, Team.where(work: '1'), :id, :team_name, {}, {class:"team-select"}) %>
<%= f.label :時間帯を選択, class: 'lavel' %>
<%= f.collection_select(:time_zone_id, TimeZone.all, :id, :name, {}, {class:"time_zone-select"}) %>
<%= f.label :サイズを選択, class: 'lavel' %>
<%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"size-select"}) %>
<%= f.label :予約確度を選択, class: 'lavel' %>
<%= f.collection_select(:accuracy_id, Accuracy.all, :id, :name, {}, {class:"accuracy-select"}) %>
<%= f.label :場所を選択, class: 'lavel' %>
<%= f.collection_select(:mie_id, Mie.all, :id, :name, {}, {class:"mie-select"}) %>
<%= f.label :連絡元を選択, class: 'lavel' %>
<%= f.collection_select(:first_contact_id, FirstContact.all, :id, :name, {}, {class:"first_contact-select"}) %>
<%= f.submit "新規で予約登録する" %>
<% end %>
<%
=end
%>

app/views/schedules/index.html.erb
<!-- 予約フォーム -->
<%= form_with model: @schedules, url: schedules_path, local: true do |f| %>
<%= f.label :日付を選択, class: 'lavel' %>
<%= f.date_field :scheduled_date, class: 'date-select' %>
<%= f.label :施工班を選択, class: 'lavel' %>
<%= f.collection_select(:team_id, Team.where(work: '1'), :id, :team_name, {}, {class:"team-select"}) %>
<%= f.label :時間帯を選択, class: 'lavel' %>
<%= f.collection_select(:time_zone_id, TimeZone.all, :id, :name, {}, {class:"time_zone-select"}) %>
<%= f.label :サイズを選択, class: 'lavel' %>
<%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"size-select"}) %>
<%= f.label :予約確度を選択, class: 'lavel' %>
<%= f.collection_select(:accuracy_id, Accuracy.all, :id, :name, {}, {class:"accuracy-select"}) %>
<%= f.label :場所を選択, class: 'lavel' %>
<%= f.collection_select(:mie_id, Mie.all, :id, :name, {}, {class:"mie-select"}) %>
<%= f.label :連絡元を選択, class: 'lavel' %>
<%= f.collection_select(:first_contact_id, FirstContact.all, :id, :name, {}, {class:"first_contact-select"}) %>
<%= f.submit "登録する" %>
<% end %>

<div class='calendarsbox'>
  <div class='calendars'>
    <div class='calendar'>
      <% @week_days.each do |day|%>
        <div class='day-item'>
          <div class='date'>
            <%= day[:month] %>/<%= day[:date] %><br><%= day[:wday] %>
          </div>
        </div>
      <% end %>
    </div>
      <!-- 稼働している班数分繰り返す -->
      <% @teams.each do |team| %>
            <!-- １班に付き午前１週間・午後１週間の2回繰り返す -->
            <% 2.times do |tz| %> 
            <% tzid = 2 + tz %>
    <div class='calendar'>
                <% @week_days.each do |day| %>
                  <div class='item'>
                    <div class='item-date'>
                      <%= day[:month] %>/<%= day[:date] %><%= day[:wday] %>
                      <%= team.team_name %>班 <%= TimeZone.find(tzid).name %>
                    </div>
                    <div class='content'>
                      <% @schedules.each do |cal| %>
                        <% if day[:scheduled_date] == cal.scheduled_date && cal.time_zone_id == tzid && cal.team_id == team.id%>
                          <div class="content_header">
                            <div class="content_detail"><%= link_to "予約詳細", schedule_path(cal.id), class: :nav__btn %></div>
                            <div class="content_detail"><%= Size.find(cal.size_id).name%></div>
                          </div>
                          <div class="content_body">
                            <% case %>
                            <% when cal.accuracy_id == 3 %> 
                                <div class="content_body_top">
                                  <div class="content_detail">時間:<%#= StartTime.find(cal.start_time_id).name%></div>
                                  <div class="content_detail">場所:<%= Mie.find(cal.mie_id).name%></div>
                                </div>
                                <div class="content_body_middle">
                                </div>
                              <%when cal.accuracy_id == 2%>
                                <div class="content_body_top">
                                  <div class="content_detail">場所:<%= Mie.find(cal.mie_id).name%></div>
                                </div>
                                <div class="content_body_middle">
                                  <div class="content_detail">これは仮予約です</div>
                                    <div class="content_detail"><%= FirstContact.find(cal.first_contact_id).name%>より問い合わせ</div>
                                </div>
                                <%when cal.accuracy_id == 4%>
                                <div class="content_body_middle">
                                  <div class="content_detail">夜間明けの班です</div>
                                </div>
                                <%end%>
                                    <% if cal.content != nil %>
                                    <div class="content_body_bottom">
                                  <div class="content_detail">コメント:有り</div>
                                </div>
                                <%end%>
                            </div>
                          <%end%>
                        <%end%>
                    </div>
                  </div>
                <% end %>
    </div>
          <% end %>
      <% end %>

<!-- 夜間工事 -->
<% @teams.each do |team| %>
    <div class='calendar'>
                <% @week_days.each do |day| %>
                  <div class='item'>
                    <div class='item-date'>
                      <%= day[:month] %>/<%= day[:date] %><%= day[:wday] %>
                      <%= team.team_name %>班 <%= TimeZone.find(4).name %>
                    </div>
                    <div class='content'>
                      <% @schedules.each do |cal| %>
                        <% if day[:scheduled_date] == cal.scheduled_date && cal.time_zone_id == 4 && cal.team_id == team.id%>
                          <div class="content_header">
                            <div class="content_detail"><%= link_to "予約詳細", schedule_path(cal.id), class: :nav__btn %></div>
                            <div class="content_detail"><%= Size.find(cal.size_id).name%></div>
                          </div>
                          <div class="content_body">
                              <% if cal.accuracy_id == 3 %> 
                                <div class="content_body_top">
                                  <div class="content_detail">時間:<%#= StartTime.find(cal.start_time_id).name%></div>
                                  <div class="content_detail">場所:<%= Mie.find(cal.mie_id).name%></div>
                                </div>
                                <div class="content_body_middle">
                                </div>
                              <%else cal.accuracy_id == 2%>
                                <div class="content_body_top">
                                  <div class="content_detail">夜明け班を確保してください<br>
                                    場所:<%= Mie.find(cal.mie_id).name%></div>
                                </div>
                                <div class="content_body_middle">
                                  <div class="content_detail">これは仮予約です</div>
                                    <div class="content_detail"><%= FirstContact.find(cal.first_contact_id).name%>より問い合わせ</div>
                                </div>
                                  <%end%>
                                    <% if cal.content != nil %>
                                    <div class="content_body_bottom">
                                  <div class="content_detail">コメント:有り</div>
                                </div>
                                <%end%>
                            </div>
                          <%end%>
                        <%end%>
                    </div>
                  </div>
                <% end %>
    </div>
    <% end %>


  </div>
</div>

app/views/schedules/new.html.erb
<%= form_with model: @schedule, url: schedules_path, local: true do |f| %>
<div class="hissu_input">必須項目</div>
<%= f.label :日付を選択, class: 'lavel' %>
<%= f.date_field :scheduled_date, class: 'date-select' %>
<%= f.label :施工班を選択, class: 'lavel' %>
<%= f.collection_select(:team_id, Team.where(work: '1'), :id, :team_name, {}, {class:"team-select"}) %>
<%= f.label :時間帯を選択, class: 'lavel' %>
<%= f.collection_select(:time_zone_id, TimeZone.all, :id, :name, {}, {class:"time_zone-select"}) %>
<%= f.label :サイズを選択, class: 'lavel' %>
<%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"size-select"}) %>
<%= f.label :予約確度を選択, class: 'lavel' %>
<%= f.collection_select(:accuracy_id, Accuracy.all, :id, :name, {}, {class:"accuracy-select"}) %>
<%= f.label :場所を選択, class: 'lavel' %>
<%= f.collection_select(:mie_id, Mie.all, :id, :name, {}, {class:"mie-select"}) %>
<%= f.label :連絡元を選択, class: 'lavel' %>
<%= f.collection_select(:first_contact_id, FirstContact.all, :id, :name, {}, {class:"first_contact-select"}) %>
<%= f.submit "登録する" %>
<% end %>

app/views/schedules/show.html.erb
予約日:<%= @schedule.scheduled_date %>
時間帯:<%= @schedule.time_zone.name %>
班:<%= @schedule.team.team_name %>
サイズ:<%= @schedule.size.name %>
予約確度:<%= @schedule.accuracy.name %>
場所:<%= @schedule.mie.name %>
連絡元:<%= @schedule.first_contact.name %>

<%= link_to "予約を変更", edit_schedule_path(@schedule.id), class: :nav__btn %>
<%= link_to "内容をコピー", edit_schedule_path(@schedule.id), class: :nav__btn %>


<%= link_to "予約を削除", schedule_path(@schedule.id), method: :delete,  class: :nav__btn  %>